global:
  message:Welcome to customer service prod environment
server:
  port:8083
message:this is hello from prod.. !
spring:
  datasource:
    url:jdbc:mysql://localhost:3306/cust_prod
    username:root
    password:Alekhya@1812
    driverClassName:com.mysql.ch.jdbc.Driver
jpa:
  hibernate:
    ddl-auto:update
  show-sql:true
