global:
  message:Welcome to customer service dev environment
server:
  port:8082
message:this is hello from dev !
spring:
  datasource:
    url:jdbc:mysql://localhost:3306/cust_dev
    username:root
    password:Alekhya@1812
    driverClassName:com.mysql.ch.jdbc.Driver
jpa:
  hibernate:
    ddl-auto:update
  show-sql:true
  
