global:
  message:Welcome to order service dev environment
server:
  port:8084
message:this is hello from order dev !
spring:
  datasource:
    url:jdbc:mysql://localhost:3306/order_dev
    username:root
    password:Alekhya@1812
    driverClassName:com.mysql.ch.jdbc.Driver
jpa:
  hibernate:
    ddl-auto:update
  show-sql:true
  
